check/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'check'

urlpatterns = [
    path('index/', views.index, name='check_index'),
    path('upload/', views.upload, name='check_upload'),
    path('wait/', views.wait, name='check_wait'),
    path('download/<str:uid>/', views.download, name='check_download'),
    url(r'^spider/download/(?P<filename>.+)$', views.getfile, name='getfile'),
]

report/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'report'
urlpatterns = [
    path('', views.home, name='home'),
    path('oauth_login/', views.oauth_login, name='oauth_login'),
    path('oauth_callback/', views.oauth_callback, name='oauth_callback'),
    path('tsinghua_auth_login/', views.tsinghua_auth_login, name='tsinghua_auth_login'),
    path('tsinghua_auth_callback/', views.tsinghua_auth_callback, name='tsinghua_auth_callback'),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='report/logged_out.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('record/', views.record_list, name='record_list'),
    path('record/add/', views.record_detail, name='record_detail'),
    path('entry/', views.entry_list, name='entry_list'),
    path('entry/add/', views.entry_detail, name='entry_detail'),
    path('entry/<int:entry_id>/', views.entry_detail, name='entry_detail'),
    path('entry/<int:entry_id>/delete/', views.entry_delete, name='entry_delete'),
    path('building/', views.building_list, name='building_list'),
    path('building/<uuid:building_uuid>/', views.building_detail, name='building_detail'),
    path('building/<uuid:building_uuid>/<date>/', views.building_detail, name='building_detail'),
]

spring2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('su/', include('django_su.urls')),
    path('', include('report.urls')),
    path('check/', include('check.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/forms.py
from django import forms
from django.core.exceptions import ValidationError

from bootstrap_datepicker_plus import DatePickerInput

from .models import Person, Record, Entry


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['idnum'].disabled = True
        self.fields['name'].disabled = True
        self.fields['affiliation'].disabled = True

    class Meta:
        model = Person
        fields = ('name', 'idnum', 'affiliation', 'phone', 'phone2', 'remark')
        widgets = {
            'remark': forms.Textarea({'placeholder': '需要向学校反映的问题或意见'}),
        }


class RecordForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].disabled = True

    class Meta:
        model = Record
        fields = ('date', 'temperature', 'has_fever', 'has_cough', 'has_wornout', 'remark')
        widgets = {
            'temperature': forms.NumberInput({'placeholder': '如无不适可留空，单位℃，保留小数点后一位', 'autofocus': True}),
            'remark': forms.Textarea({'placeholder': '在此填写其他不适症状'}),
        }

    def clean(self):
        data = super().clean()
        if 'healthy' in self.data:
            if data['has_fever'] or data['has_cough'] or data['has_wornout']:
                raise ValidationError('无症状才能点击“一切正常！”按钮', 'invalid-state')
        return data

class EntryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['building'].queryset = self.fields['building'].queryset.order_by('-weight', 'name')

    class Meta:
        model = Entry
        fields = ('date', 'building', 'room', 'purpose')
        widgets = {
            'date': DatePickerInput(options={
                'format': 'YYYY/MM/DD',
                'locale': 'zh-CN',
            }),
        }

report/views.py
import datetime
import pathlib

from django.shortcuts import render, redirect
from django.conf import settings
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

import requests
from requests_oauthlib import OAuth2Session
from django_tables2 import RequestConfig
from django_tables2.export import TableExport

from . import utils
from .models import Person, Record, Entry, Building
from .forms import ProfileForm, RecordForm, EntryForm
from .tables import RecordTable, EntryTable, BuildingTable, BuildingEntryTable


def oauth_login(request):
    redirect_uri = request.build_absolute_uri(reverse('report:oauth_callback'))
    redirect_uri = redirect_uri.replace('http://', 'https://')  # XXX: Enforce HTTPS
    oauth = OAuth2Session(
        settings.OAUTH_CLIENT_ID,
        redirect_uri=redirect_uri,
    )
    authorization_url, state = oauth.authorization_url(settings.OAUTH_AUTHORIZE_URL)
    request.session['oauth_state'] = state
    return redirect(authorization_url)


def oauth_callback(request):
    redirect_uri = request.build_absolute_uri(reverse('report:oauth_callback'))
    redirect_uri = redirect_uri.replace('http://', 'https://')  # XXX: Enforce HTTPS
    oauth = OAuth2Session(
        settings.OAUTH_CLIENT_ID,
        redirect_uri=redirect_uri,
        state=request.session['oauth_state'],
    )
    authorization_response = request.build_absolute_uri()
    authorization_response = authorization_response.replace('http://', 'https://')  # XXX: Enforce HTTPS
    token = oauth.fetch_token(
        settings.OAUTH_ACCESS_TOKEN_URL,
        client_secret=settings.OAUTH_CLIENT_SECRET,
        authorization_response=authorization_response,
    )
    request.session['oauth_token'] = token
    response = oauth.request('GET', settings.OAUTH_USER_INFO_URL)
    data = response.json()
    idnum = data['user']['student_id']
    try:
        user = utils.get_or_create_user(idnum)
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    except Person.DoesNotExist:
        messages.warning(request, '工作证号 {} 不在数据库中，请与本单位信息员联系。'.format(idnum))
    return redirect('report:home')


def tsinghua_auth_login(request):
    ipaddr = utils.get_client_ip(request).replace('.', '_')
    request.session['ipaddr'] = ipaddr
    url = settings.TSINGHUA_AUTH_LOGIN_URL.format(
        appid_md5=settings.TSINGHUA_AUTH_APPID_MD5,
        seq=settings.TSINGHUA_AUTH_SEQ,
        callback_url=reverse('report:tsinghua_auth_callback'),
    )
    return redirect(url)


def tsinghua_auth_callback(request):
    ticket = request.GET['ticket']
    url = settings.TSINGHUA_AUTH_AUTHORIZE_URL.format(
        appid=settings.TSINGHUA_AUTH_APPID,
        ticket=ticket,
        ipaddr=request.session['ipaddr'],
    )
    resp = requests.get(url)
    with (pathlib.Path(settings.BASE_DIR) / 'var' / 'tsinghua_auth.log').open('a') as log_file:
        log_file.write('{} {}\n'.format(datetime.datetime.now(), resp.text))
    data = {k: v for k, v in [p.split('=') for p in resp.text.split(':')]}
    code = data.get('code')
    if code == '0':
        idnum = data['zjh']
        try:
            user = utils.get_or_create_user(idnum)
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        except Person.DoesNotExist:
            messages.warning(request, '工作证号 {} 不在数据库中，请与本单位信息员联系。'.format(idnum))
    else:
        messages.error(request, '清华统一用户登录系统返回代码错误（{}），请与系统管理员联系。'.format(code))
        print('Tsinghua auth error: {}'.format(resp.text))
    return redirect('report:home')


def login(request):
    return render(request, 'report/login.html')


@login_required
def home(request):
    return render(request, 'report/home.html')


@login_required
def profile(request):
    person = request.user.person
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            messages.success(request, '信息提交成功。')
            return redirect('report:home')
    else:
        form = ProfileForm(instance=person)
    return render(request, 'report/profile.html', {'form': form})


@login_required
def record_list(request):
    person = getattr(request.user, 'person')
    table = RecordTable(person.record_set.filter(is_submitted=True))
    RequestConfig(request).configure(table)
    return render(request, 'report/record_list.html', {'table': table})


@login_required
def record_detail(request):
    person = getattr(request.user, 'person')
    record, _ = Record.objects.get_or_create(
        person=person,
        date=utils.local_date(timezone.now() + settings.RECORD_OFFSET),
        defaults={'ip': utils.get_client_ip(request)},
    )
    if request.method == 'POST':
        form = RecordForm(request.POST, instance=record)
        if form.is_valid():
            record = form.save(commit=False)
            record.is_submitted = True
            record.save()
            messages.success(request, '健康打卡成功。')
            return redirect('report:record_list')
    else:
        form = RecordForm(instance=record)
    return render(request, 'report/record_detail.html', {'form': form, 'submitted': record.is_submitted})


@login_required
def entry_list(request):
    person = getattr(request.user, 'person')
    table = EntryTable(person.entry_set.all())
    RequestConfig(request).configure(table)
    return render(request, 'report/entry_list.html', {'table': table})


@login_required
def entry_detail(request, entry_id=None):
    person = getattr(request.user, 'person')
    entry = None if entry_id is None else person.entry_set.get(pk=entry_id)
    if request.method == 'POST':
        form = EntryForm(request.POST, instance=entry)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.person = person
            entry.approve1_decision = None
            entry.approve1_person = None
            entry.approve1_time = None
            entry.approve2_decision = None
            entry.approve2_person = None
            entry.approve2_time = None
            entry.approve3_decision = None
            entry.approve3_person = None
            entry.approve3_time = None
            entry.save()
            messages.success(request, '申请提交成功。')
            return redirect('report:entry_list')
    else:
        initial = {'date': utils.local_date(timezone.now() + settings.ENTRY_OFFSET)}
        last = person.entry_set.order_by('add_time').last()
        if last:
            initial['building'] = last.building
            initial['room'] = last.room
            initial['purpose'] = last.purpose
        form = EntryForm(instance=entry, initial=initial)
    return render(request, 'report/entry_detail.html', {'form': form})


@login_required
def entry_delete(request, entry_id):
    person = getattr(request.user, 'person')
    entry = person.entry_set.get(pk=entry_id)
    entry.delete()
    return redirect('report:entry_list')


@login_required
def building_list(request):
    table = BuildingTable(Building.objects.all())
    RequestConfig(request).configure(table)
    return render(request, 'report/building_list.html', {'table': table})


def building_detail(request, building_uuid, date=None):
    if date:
        date = datetime.datetime.strptime(date, '%Y-%m-%d').date()
    else:
        date = timezone.localdate()
    building = Building.objects.get(uuid=building_uuid)
    entries = building.entry_set.filter(date=date, approve3_decision=True)
    table = BuildingEntryTable(entries)
    RequestConfig(request, paginate=False).configure(table)
    export_format = request.GET.get('_export', None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table)
        return exporter.response('{}.{}'.format(date, export_format))
    context = {
        'building': building,
        'date': date,
        'prev_day': date - datetime.timedelta(days=1),
        'next_day': date + datetime.timedelta(days=1),
        'table': table,
    }
    return render(request, 'report/building_detail.html', context)

report/templates/report/base.html
{% load static %}
{% load bootstrap4 %}
{% load stringmethods %}
<!DOCTYPE html>
<html lang="zh-Hans">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block extrahead %}{% endblock %}
    <title>计算机系党委疫情防控信息系统</title>
  </head>
  <body>
    <div id="main" class="container">
      {% if user.is_authenticated %}
      <p>{{ user.person.name }}老师，您好！</p>
      <p>
        <a class="mb-1 btn btn{% if request.path != '/' %}-outline{% endif %}-primary" href="{% url 'report:home' %}">首页</a>
        <a class="mb-1 btn btn{% if not request.path|startswith:'/record/' %}-outline{% endif %}-primary" href="{% url 'report:record_list' %}">每日健康打卡</a>
        <a class="mb-1 btn btn{% if not request.path|startswith:'/entry/' %}-outline{% endif %}-primary" href="{% url 'report:entry_list' %}">进入楼宇申请</a>
        <a class="mb-1 btn btn{% if not request.path|startswith:'/profile/' %}-outline{% endif %}-primary" href="{% url 'report:profile' %}">个人基本信息</a>
        {% if user.is_staff %}<a class="mb-1 btn btn-outline-danger" href="{% url 'admin:index' %}">管理</a>{% endif %}
        <a class="mb-1 btn btn-outline-secondary" href="{% url 'report:logout' %}">退出</a>
      </p>
      {% endif %}
      {% bootstrap_messages %}
      <h3>{% block header %}{% endblock %}</h3>
      {% block content %}{% endblock %}
      <div class="footer">
        <hr>
        <p>&copy; 2020 清华大学计算机科学与技术系</p>
      </div>
    </div>
  </body>
</html>

report/templates/report/building_detail.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}
{% load django_tables2 %}

{% block header %}进入楼宇申请审批结果{% endblock %}
{% block content %}
<p class="lead">
楼宇：{{ building.name }}<br>
日期：{{ date }}<br>
</p>
<p>
<a class="mb-1 btn btn-outline-primary" href="{% url 'report:building_detail' building.uuid prev_day %}">前一天</a>
<a class="mb-1 btn btn-outline-primary" href="{% url 'report:building_detail' building.uuid %}">今天</a>
<a class="mb-1 btn btn-outline-primary" href="{% url 'report:building_detail' building.uuid next_day %}">后一天</a>
<a class="mb-1 btn btn-primary" href="{% export_url 'xlsx' %}">导出为 Excel 文件</a>
</p>
{% render_table table %}
{% endblock %}

report/templates/report/building_list.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block header %}楼宇列表{% endblock %}
{% block content %}
{% render_table table %}
{% endblock %}

report/templates/report/entry_detail.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block header %}进入楼宇申请{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='提交' %}<a href="{% url 'report:entry_list' %}" class="btn btn-outline-secondary ml-1">返回</a>{% endbuttons %}
</form>
{% endblock %}

report/templates/report/entry_list.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block header %}进入楼宇申请{% endblock %}
{% block content %}
<p><a href="{% url 'report:entry_detail' %}" class="btn btn-primary">新的申请</a></p>
{% render_table table %}
<p class="text-warning">注意：进行修改操作后审批状态将会重置。</p>
{% endblock %}

report/templates/report/home.html
{% extends 'report/base.html' %}

{% block header %}首页{% endblock %}
{% block content %}
<p class="lead">欢迎使用计算机系党委疫情防控信息系统</p>
{% endblock %}

report/templates/report/logged_out.html
{% extends 'report/base.html' %}

{% block header %}退出{% endblock header %}
{% block content %}
<p>成功退出。点击<a href="{% url 'report:home' %}">这里</a>返回首页（可能需要重新认证）。</p>
{% endblock %}

report/templates/report/login.html
{% extends 'report/base.html' %}

{% block header %}登录{% endblock %}
{% block content %}
<p>
<a href="{% url 'report:oauth_login' %}" class="mb-1 btn btn-outline-primary">使用酒井 ID 认证登录</a>
</p>
<p>提示：在酒井 ID 认证页面中，如果在微信内请点击“微信登录”，否则请点击“清华 ID 登录”。</p>
{% endblock %}

report/templates/report/profile.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block header %}个人基本信息{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='提交' %}{% endbuttons %}
</form>
{% endblock %}

report/templates/report/record_detail.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block header %}每日健康打卡{% endblock %}
{% block content %}
<form method="post">
  {% buttons %}
  {% if not submitted %}
  <button class="btn btn-primary" type="submit" name="healthy">一切正常！</button>
  <small class="form-text text-muted">如果身体状况正常，可直接点击上面的“一切正常！”按钮。</small>
  {% else %}
  <button class="btn btn-primary" disabled>今日已打卡</button>
  {% endif %}
  {% endbuttons %}
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit=submitted|yesno:'修改,提交' %}<a href="{% url 'report:record_list' %}" class="btn btn-outline-secondary ml-1">返回</a>{% endbuttons %}
</form>
{% endblock %}

report/templates/report/record_list.html
{% extends 'report/base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block header %}每日健康打卡{% endblock %}
{% block content %}
<p><a href="{% url 'report:record_detail' %}" class="btn btn-primary">今日打卡</a></p>
{% render_table table %}
{% endblock %}