check/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'check'

urlpatterns = [
    path('index/', views.index, name='check_index'),
    path('upload/', views.upload, name='check_upload'),
    path('wait/', views.wait, name='check_wait'),
    path('download/<str:uid>/', views.download, name='check_download'),
    url(r'^spider/download/(?P<filename>.+)$', views.getfile, name='getfile'),
]

notice/urls.py
from django.urls import path

from . import views

app_name = 'notice'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
]

spring2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('su/', include('django_su.urls')),
    path('', include('report.urls')),
    path('check/', include('check.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.db import models

from report.models import Person


class Notice(models.Model):
    title = models.CharField('标题', max_length=100)
    content = models.TextField('内容')
    post_time = models.DateTimeField('发布时间')
    source = models.CharField('来源', max_length=100)
    source_url = models.URLField('原始链接', blank=True)
    published = models.BooleanField('是否公布')
    to_ack = models.BooleanField('是否需要确认', default=False)
    marked = models.BooleanField('重要标记', default=False)
    read_count = models.IntegerField('阅读次数', default=0)
    add_time = models.DateTimeField('添加时间', auto_now_add=True)
    update_time = models.DateTimeField('修改时间', auto_now=True)
    acked_persons = models.ManyToManyField(
        Person, through='Ack', related_name='acked_notices',
        verbose_name='已确认人员',
    )

    class Meta:
        verbose_name = '通知'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Ack(models.Model):
    notice = models.ForeignKey(Notice, models.CASCADE, verbose_name='通知')
    person = models.ForeignKey(Person, models.CASCADE, verbose_name='人员')
    add_time = models.DateTimeField('添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '确认'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{} * {}'.format(self.notice, self.person)


def notice_attachment_path(instance, filename):
    return 'notice/{notice_id}/{filename}'.format(
        notice_id=instance.notice.id,
        filename=filename,
    )

class Attachment(models.Model):
    notice = models.ForeignKey(Notice, models.CASCADE, verbose_name='通知')
    file = models.FileField('文件', upload_to=notice_attachment_path)
    weight = models.IntegerField('权重', default=0, help_text='决定附件排序，越大越靠前。')
    add_time = models.DateTimeField('添加时间', auto_now_add=True)
    update_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '附件'
        verbose_name_plural = verbose_name
        ordering = ('-weight', 'file')

    def basename(self):
        pos = self.file.name.rfind('/')
        return self.file.name[pos + 1:]

    def __str__(self):
        return str(self.file)

notice/forms.py
from django import forms


class AckForm(forms.Form):
    acked = forms.BooleanField(label='我已阅读')

notice/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render, redirect
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Notice, Ack
from .forms import AckForm


@login_required
def index(request):
    return render(request, 'notice/index.html', {
        'notices': Notice.objects.filter(published=True).order_by('-post_time'),
    })


@login_required
def detail(request, pk):
    notice = get_object_or_404(Notice, pk=pk, published=True)
    person = request.user.person
    if request.method == 'POST':
        form = AckForm(request.POST)
        if form.is_valid():
            Ack.objects.update_or_create(
                notice=notice,
                person=person,
            )
            messages.success(request, '已确认阅读该通知。')
            return redirect('report:home')
    else:
        form = AckForm()
        notice.read_count = F('read_count') + 1
        notice.save(update_fields=('read_count',))
        notice.refresh_from_db(fields=('read_count',))
    return render(request, 'notice/detail.html', {
        'notice': notice,
        'form': form,
    })

notice/templates/notice/detail.html
{% extends 'report/base.html' %}
{% load markdownify %}
{% load crispy_forms_tags %}
{% load notice_ack %}

{% block header %}通知详情{% endblock %}
{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ notice.title }}</h5>
    <p class="text-secondary">来源：{{ notice.source }}<br>
    {% if notice.source_url %}原始链接：<a href="{{ notice.source_url }}">{{ notice.source_url }}</a><br>{% endif %}
    发布时间：{{ notice.post_time|date }}<br>
    阅读次数：{{ notice.read_count }}</p>
    <div class="card-text">{{ notice.content|markdownify }}</div>
    {% if notice.attachment_set.exists %}
    <p>附件：</p>
    <ul>
    {% for attachment in notice.attachment_set.all %}
    <li><a href="{{ MEDIA_URL }}{{ attachment.file.name }}">{{ attachment.basename }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% if notice.to_ack %}
<div class="mt-3">
  {% if not notice|acked_by:user %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">确认</button>
  </form>
  {% else %}
  <button class="btn btn-primary" disabled>已确认</button>
  {% endif %}
</div>
{% endif %}
{% endblock %}

notice/templates/notice/index.html
{% extends 'report/base.html' %}
{% load notice_ack %}

{% block header %}所有通知{% endblock %}
{% block content %}
<ul>
{% for notice in notices %}
<li>
{% if not notice|acked_by:user %}<strong>{% endif %}
<a href="{% url 'notice:detail' notice.id %}">{{ notice.title }}</a>，{{ notice.source }}，{{ notice.post_time|date }}，阅读 {{ notice.read_count }} 次
{% if not notice|acked_by:user %}</strong>{% endif %}
</li>
{% endfor %}
</ul>
{% endblock %}